[package]
name = "aloroid/markdown"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = [".gitattributes", ".gitignore", "README.md"]
include = ["src"]

[dependencies]
